apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
spec:
  host: frontend-edu3.apps.211-43-12-210.nip.io
  port:
    targetPort: 80
#  tls:
#    insecureEdgeTerminationPolicy: Redirect
#    termination: passthrough
  to:
    kind: Service
    name: frontend
    weight: 100    
  wildcardPolicy: None  
